name: java-springboot-CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
              
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    # - name: Lint with mvn sonar
    #   run: mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      
    - name: Build Docker image
      run: |
        export IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c 1-7)
        docker build -t java-spring-app:$IMAGE_TAG .
               
    - name: Add git tag
      run: git tag -a $IMAGE_TAG -m "Release $IMAGE_TAG"
      env:
        IMAGE_TAG: ${{ steps.build.outputs.IMAGE_TAG }}
        
    - name: Push git tag
      run: git push origin $IMAGE_TAG
      env:
        IMAGE_TAG: ${{ steps.build.outputs.IMAGE_TAG }}
        
    - name: Login to ECR
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 190168171128.dkr.ecr.eu-west-1.amazonaws.com
      
    - name: Push Docker image to ECR
      if: github.ref == 'refs/heads/master'
      run: |
        export IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c 1-7)
        docker tag java-spring-app:$IMAGE_TAG 190168171128.dkr.ecr.eu-west-1.amazonaws.com/java-app:$IMAGE_TAG
        docker push 190168171128.dkr.ecr.eu-west-1.amazonaws.com/java-app:$IMAGE_TAG
      env:
        IMAGE_TAG: ${{ steps.build.outputs.IMAGE_TAG }}
